name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './rdp-manager/package-lock.json'

      - name: Install dependencies
        working-directory: ./rdp-manager
        run: |
          npm ci
          npm install -g electron-builder

      - name: Build Application
        working-directory: ./rdp-manager
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: electron-builder --win --publish never
        shell: pwsh 