name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only run for tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './rdp-manager/package-lock.json'

      - name: Install dependencies
        working-directory: ./rdp-manager
        run: |
          npm ci
          npm install -g electron-builder

      - name: Build Application
        working-directory: ./rdp-manager
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: electron-builder --win
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            rdp-manager/dist/*.exe
            rdp-manager/dist/latest.yml
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: windows-latest
    if: "!startsWith(github.ref, 'refs/tags/')"  # Only run for non-tag pushes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './rdp-manager/package-lock.json'

      - name: Install dependencies
        working-directory: ./rdp-manager
        run: |
          npm ci
          npm install -g electron-builder

      - name: Build Application
        working-directory: ./rdp-manager
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: electron-builder --win --publish never
        shell: pwsh 